image: node:9.11

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

before_script:
  - npm install
  - npm install -g truffle@4.1.13

build:
  stage: build
  script:
    - truffle compile
    - npm run-script build
  artifacts:
    paths:
      - build_webpack/

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - ls -l build_webpack/
