image: node:9.11

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  before_script:
    - npm install
    - npm install -g truffle@4.1.13
  script:
    - truffle compile
    - npm run-script build
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/mikiquantum/simple-dapp-calculator .
    - docker push registry.gitlab.com/mikiquantum/simple-dapp-calculator
  artifacts:
    paths:
      - build_webpack/

deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - echo "Deploying"
